version: '3.4'

services:
  masterdb:
    container_name: masterdb
    environment:
      SA_PASSWORD: "P@ssw0rd1s5tr0n9"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd1s5tr0n9' -Q 'select 1'"]
      interval: 10s
      timeout: 10s
      retries: 3
  masterdata.api:
    container_name: masterdata.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__MasterDataConnectionString=Server=masterdb;Database=MasterDb;User Id=sa;Password=P@ssw0rd1s5tr0n9;TrustServerCertificate=True"
    depends_on:
      - masterdb
    ports:
      - "3100:3100"
      