services:
  masterdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  masterdata.api:
    image: masterdata.api
    build:
      context: .
      dockerfile: Services/MasterData.Api/Dockerfile