@host = http://localhost:5029

POST {{host}}/auth/login
Content-Type: application/json

{
  "firstName": "Tran",
  "lastName": "The Duy",
  "email": "vip.theduy1307@gmail.com",
  "password": "Admin@123"
}
###
